FROM jenkins
MAINTAINER DANIEL "danielnanuk@gmail.com"
ENV REFRESHED_AT 2016-01-21

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt


